GET http://127.0.0.1:8000/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NjE5NDI1LCJpYXQiOjE3NTg2MTkxMjUsImp0aSI6ImFmMjA4NDA2MGE4MDQ4NjhiOWYyY2QwYWI4ZWZmMzM0IiwidXNlcl9pZCI6Mn0.Zf8WUwPqqobfROTuV5MSR-zOVLXz6AwVcW-HrdJ6JHQ

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}


###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type:application/json

{
    "username":"admin",
    "password":"test"
}


###
GET http://127.0.0.1:8000/products/3/ HTTP/1.1

###
PUT http://127.0.0.1:8000/products/3/ HTTP/1.1
Content-Type:application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NjQxMjExLCJpYXQiOjE3NTg2NDA5MTEsImp0aSI6IjI1MDRmYzAwYjNkNTRkNjg5ZTI3ODBjODg3ODhiMjkzIiwidXNlcl9pZCI6MX0.Ukp94SaWPM3cC7oxTJ33ZLozIFLr2aO-8wIGRO_XhIc

{
    "name": "updated_product",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new book"
}


###
DELETE  http://127.0.0.1:8000/products/3/ HTTP/1.1
